import React from 'react';
import { HourlyForecastScroll } from '../components/dashboard/HourlyForecastScroll';
import { DailyForecastList } from '../components/dashboard/DailyForecastList';
import { useWeatherStore } from '../store/useWeatherStore';
import { Calendar, Info } from 'lucide-react';

export const ForecastPage: React.FC = () => {
  const { currentLocation } = useWeatherStore();

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-[#17352A] flex items-center gap-2">
            <Calendar className="w-6 h-6 text-[#2E7D5B]" />
            Weather Forecast Center — {currentLocation.name}
          </h1>
          <p className="text-xs text-[#6B7D74]">
            High-resolution 24-hour nowcast and 7-day district meteorological outlook
          </p>
        </div>

        <div className="bg-[#E8F5EE] border border-[#6BAF92]/40 text-[#2E7D5B] px-3 py-1.5 rounded-xl text-xs font-semibold self-start sm:self-auto">
          Source: IMD Regional Meteorological Centre
        </div>
      </div>

      <HourlyForecastScroll />

      <DailyForecastList />

      <div className="bg-white border border-[#DCEAE2] rounded-2xl p-5 shadow-xs space-y-2 text-xs text-[#6B7D74]">
        <div className="font-bold text-[#17352A] flex items-center gap-1.5">
          <Info className="w-4 h-4 text-[#2E7D5B]" /> Meteorological Forecast Policy
        </div>
        <p className="leading-relaxed">
          Operational forecasts are generated by combining India Meteorological Department (IMD) high-resolution regional models with ECMWF ensemble validation. Numerical precipitation predictions are updated every 3 hours.
        </p>
      </div>
    </div>
  );
};
